"""Project-owned 3D Gaussian training contracts."""

from .checkpoint import (
    ATTEMPT_SCHEMA_VERSION,
    CHECKPOINT_SCHEMA_VERSION,
    AttemptRecord,
    CheckpointContractError,
    CheckpointProvenance,
    CheckpointRecord,
    CheckpointReference,
    CheckpointState,
    LoadedCheckpoint,
    checkpoint_dir,
    create_attempt,
    load_attempt,
    load_checkpoint,
    select_retained_checkpoints,
    write_checkpoint,
)
from .config import (
    CONFIG_SCHEMA_VERSION,
    PUBLIC_PROFILES,
    GaussianConfigError,
    ResolvedGaussianConfig,
    assert_single_field_ablation,
    canonical_config_json,
    effective_config_hash,
    resolve_internal_config,
    resolve_public_config,
    resolved_config_record,
    validate_effective_config,
)
from .dataset import (
    DatasetContractError,
    build_colmap_contract,
    deterministic_spatial_split,
    validate_contract,
    write_contract,
)

__all__ = [
    "ATTEMPT_SCHEMA_VERSION",
    "CHECKPOINT_SCHEMA_VERSION",
    "CONFIG_SCHEMA_VERSION",
    "PUBLIC_PROFILES",
    "AttemptRecord",
    "CheckpointContractError",
    "CheckpointProvenance",
    "CheckpointRecord",
    "CheckpointReference",
    "CheckpointState",
    "DatasetContractError",
    "GaussianConfigError",
    "LoadedCheckpoint",
    "ResolvedGaussianConfig",
    "assert_single_field_ablation",
    "build_colmap_contract",
    "canonical_config_json",
    "checkpoint_dir",
    "create_attempt",
    "deterministic_spatial_split",
    "effective_config_hash",
    "load_attempt",
    "load_checkpoint",
    "resolve_internal_config",
    "resolve_public_config",
    "resolved_config_record",
    "select_retained_checkpoints",
    "validate_contract",
    "validate_effective_config",
    "write_checkpoint",
    "write_contract",
]
